spring:
  application:
    name: finance-aggregator-service

server:
  port: 8080

api:
  frankfurter:
    base-url: https://api.frankfurter.dev/v1
    connect-timeout-ms: 3000
    response-timeout-ms: 5000

finance:
  retry:
    count: 3
    delay-ms: 2000
  resources:
    latest:
      base: IDR
      currency: USD
    historical:
      range: 2024-01-01..2024-01-05
      from: IDR
      to: USD

github:
  username: "evanahmad"

app:
  timestamp-format: "yyyy-MM-dd'T'HH:mm:ss.SSXXX"

logging:
  level:
    root: INFO